version: '3.8'

services:
  app:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile.app
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html
    
  jenkins:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile.jenkins
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
  jenkins_home: